# Generated by Django 2.0 on 2019-11-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_inputreviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inputreviews',
        ),
    ]
