# Generated by Django 2.0 on 2019-11-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20191111_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13)),
                ('reg', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('rated', models.IntegerField(default=0, max_length=5)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
