# Generated by Django 2.0 on 2019-11-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colg_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='accounts/images')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='rated',
            field=models.IntegerField(default=0),
        ),
    ]
